-- Seed data for portfolio

-- Insert blocks for About page
INSERT INTO blocks (id, page_id, block_type, content, sort_order, created_at, updated_at) VALUES
('block_about_1', 'about', 'text', '{"text": "hey… wait, who even are you?"}', 0, datetime('now'), datetime('now')),
('block_about_2', 'about', 'text', '{"text": "whatever. this is my page."}', 1, datetime('now'), datetime('now')),
('block_about_3', 'about', 'text', '{"text": "you''ll probably find me in my natural habitat, which is... more figma tabs open than my chrome tabs, three terminals yelling at me like a toxic boyfriend, and a server in the corner that i swear is about to catch fire. what''s running on it? good question!"}', 2, datetime('now'), datetime('now')),
('block_about_4', 'about', 'text', '{"text": "sometimes i''m designing ui that looks like it got stolen from an apple keynote b-roll, other times i''m obsessing over micro-interactions in a UI that only three people (at best) will ever see, sometimes i''m elbow-deep in sysadmin hell, trying to get postfix and rspamd to stop acting like divorced parents and just \"please talk to each other\" (spoiler: they won''t). sometimes i''m inventing entire alphabets for languages nobody speaks, because apparently normal hobbies weren''t enough for me (don''t even ask)."}', 3, datetime('now'), datetime('now')),
('block_about_5', 'about', 'text', '{"text": "there are nights where i patch my kernel at 4am because apparently i like pain and sleep is optional. mornings where i''m debugging docker like it personally wronged me. afternoons where i''m asking myself \"what if i rebuilt the internet?\" and then immediately regretting opening vs code."}', 4, datetime('now'), datetime('now')),
('block_about_6', 'about', 'text', '{"text": "my ecosystem is chaos wrapped in vibes. design systems. self-hosted stacks. side projects that spiraled wayyyy too far. clean but casual aesthetics duct-taped onto servers running on my last shred of patience and prayers."}', 5, datetime('now'), datetime('now')),
('block_about_7', 'about', 'text', '{"text": "so if you''re just scrolling through my projects, cool. if you wanna argue about linux distros, build something cursed, or help me figure out why my minecraft server keeps imploding on day 3… then yeah, we''ll probably get along."}', 6, datetime('now'), datetime('now')),
('block_about_8', 'about', 'text', '{"text": "ok that''s enough about me. your turn."}', 7, datetime('now'), datetime('now')),
('block_about_9', 'about', 'text', '{"text": "xoxo,"}', 8, datetime('now'), datetime('now')),
('block_about_10', 'about', 'text', '{"text": "your kris <3"}', 9, datetime('now'), datetime('now'));

-- Insert blocks for Skills page
INSERT INTO blocks (id, page_id, block_type, content, sort_order, created_at, updated_at) VALUES
('block_skills_1', 'skills', 'heading', '{"text": "things i bring to the team", "level": "h2"}', 0, datetime('now'), datetime('now')),
('block_skills_2', 'skills', 'list', '{"items": ["i''m both a designer and programmer so i understand how both work.", "i don''t just make things pretty, i design workflows, ecosystems, and infrastructure that scales.", "i love breaking things down, debugging messy issues, and finding clean solutions.", "from conlangs, to product branding, i bring imagination that makes projects stand out", "i''ve run servers (both on-prem and on hetzner), messed with kernels, so i understand the whole \"under the hood\" side of tech.", "i pick up new tools and languages quickly, and i actually enjoy the learning curve.", "whether it''s explaining design to devs or dev to designers, i can act as a bridge between worlds.", "i''m a night owl and can work odd hours if needed.", "i obsess over every micro-detail so the end result feels polished, not rushed.", "i''m not afraid to admit when i don''t know something, and i''m always eager to learn more.", "i care about accessibility, usability, and making sure things just work for everyone."]}', 1, datetime('now'), datetime('now'));

-- Insert existing projects
INSERT INTO projects (id, name, slug, url, description, long_description, color, status, screenshots, technologies, featured, sort_order, created_at, updated_at) VALUES
('proj_ave', 'Ave', 'ave', 'https://aveid.net', 'Not another login. Not another password. Just you. A clean, secure identity system with no tracking, no profiles, no middlemen. Just a way to prove who you are and connect safely anywhere.', 'Ave is a privacy-focused identity system that lets you sign in anywhere without passwords. No tracking, no profiles, just secure authentication with a swipe.', '#0D99FF', 'active', '[]', '["TypeScript", "React", "Cloudflare Workers", "D1", "R2"]', 1, 0, datetime('now'), datetime('now')),
('proj_raffi', 'Raffi', 'raffi', 'https://raffi.al', 'A beautiful streaming app that actually looks good. Watch your favorite content with a sleek, modern interface that puts design first.', 'Raffi is a streaming application focused on beautiful design and user experience. Watch your favorite content with an interface that actually looks good.', '#FF6B6B', 'active', '[]', '["React", "TypeScript", "Node.js"]', 1, 1, datetime('now'), datetime('now')),
('proj_raday', 'Raday', 'raday', 'https://raday.app', 'A workspace for your projects. Simple project management with tasks, documents, and folders for people who want to get things done without the clutter. Dark by default, keyboard-first, and built for people who spend all day at their computer.', 'Raday is a project management workspace designed for developers and power users. Dark mode by default, keyboard-first navigation, and a clean interface that stays out of your way.', '#9747FF', 'active', '[]', '["TypeScript", "React", "PostgreSQL", "tRPC"]', 1, 2, datetime('now'), datetime('now')),
('proj_nook', 'Nook', 'nook', 'https://nook.you', 'Your quiet place on the internet. A private, cozy space for your thoughts, memories, and moods. Write daily journals, stories, pages, or poems, public or private. Privacy-first, designed for feelings, and soft unlike anything else.', 'Nook is a privacy-first journaling and writing platform. A cozy digital space for your thoughts, memories, and creative writing. Soft aesthetics meet serious privacy.', '#0DCB7D', 'active', '[]', '["TypeScript", "React", "SQLite", "E2E Encryption"]', 1, 3, datetime('now'), datetime('now')),
('proj_stator', 'Stator', 'stator', 'https://stator.sh', 'Control plane for your apps. Track real-time status, automate workflows with rules, toggle feature flags remotely, and collect feature requests and bug reports. All in one unified place.', 'Stator is a unified control plane for managing your applications. Real-time status monitoring, workflow automation, feature flags, and user feedback collection in one place.', '#FF9F43', 'active', '[]', '["TypeScript", "Go", "PostgreSQL", "WebSockets"]', 0, 4, datetime('now'), datetime('now')),
('proj_flick', 'Flick', 'flick', 'https://www.npmjs.com/package/runflick', 'A programming language I built from scratch. Because apparently normal hobbies weren''t enough and I needed to understand how compilers work the hard way.', 'Flick is a custom programming language built from scratch. A journey into compiler design and language implementation. Available on npm for the curious.', '#F368E0', 'active', '[]', '["Rust", "LLVM", "Compiler Design"]', 0, 5, datetime('now'), datetime('now')),
('proj_limbo', 'Limbo', 'limbo', 'https://github.com/kaleidal/limbo', 'Download manager meets browser. Like JDownloader but with a built-in browsing experience so you can grab what you need without switching apps.', 'Limbo combines a download manager with a built-in browser experience. Download files without constantly switching between applications.', '#54A0FF', 'active', '[]', '["Electron", "TypeScript", "React"]', 0, 6, datetime('now'), datetime('now')),
('proj_muffle', 'Muffle', 'muffle', 'https://github.com/kaleidal/muffle', 'A Spotify client that doesn''t suck. Custom UI, better controls, and the experience Spotify should have shipped but didn''t.', 'Muffle is an alternative Spotify client with a custom UI and improved controls. The Spotify experience that should have existed.', '#1DB954', 'active', '[]', '["Electron", "React", "Spotify API"]', 0, 7, datetime('now'), datetime('now')),
('proj_conlanger', 'Conlanger', 'conlanger', 'https://www.conlanger.site/', 'Create your own constructed languages. Realtime collaboration, guided workflows, and everything you need to build your next conlang. Powered by Convex and Ave.', 'Conlanger is a collaborative platform for creating constructed languages. Real-time collaboration, phonology tools, grammar systems, and more.', '#E056FD', 'active', '[]', '["TypeScript", "React", "Convex", "Ave Auth"]', 0, 8, datetime('now'), datetime('now')),
('proj_monkeys', 'Monkeys', 'monkeys', 'https://monkeys.rs', 'Party games for you and your friends. Host a lobby, pick a game like Monkeys Against Humanity or Skeddadle, and play, laugh, repeat. Still cooking this one.', 'Monkeys is a party game platform for playing games with friends online. Host lobbies, play various party games, and have fun together.', '#FF6B6B', 'wip', '[]', '["Rust", "WebSockets", "React"]', 0, 9, datetime('now'), datetime('now'));

-- Insert default settings
INSERT INTO settings (key, value, updated_at) VALUES
('site_name', 'Kristof''s Portfolio', datetime('now')),
('site_description', 'Designer and developer who loves clean, casual aesthetics', datetime('now')),
('contact_email', 'kristof@lanth.me', datetime('now'));
